### ISSUE TITLE
Fails to compile due to multiple definition of `dispatch_to_wsp'

### ISSUE THREAD

**Issue by SeanPesce** [Phonebooth/kannel#1]
Attempting to compile this on the latest Debian with `./configure ; make` results in the following error:

```
/usr/bin/ld: libwap.a(wtp_resp.o):kannel/wap/wtp_resp.c:100: multiple definition of `dispatch_to_wsp'; libgw.a(wap_push_ota.o):kannel/gw/wap_push_ota.c:116: first defined here
collect2: error: ld returned 1 exit status
make: *** [Makefile:365: gw/wapbox] Error 1
```

Luckily it's an easy fix. Simply change line 100 of `wap/wtp_resp.c` from:

```c
wap_dispatch_func_t *dispatch_to_wsp;
```

to:

```c
extern wap_dispatch_func_t *dispatch_to_wsp;
```

**Comment by jessestimpson** [comment]
Hi @SeanPesce, this project is a fork from https://www.kannel.org/ . We ended up not using our fork for anything; thanks for your input, but we suggest following the official package for this project.
